# 配置当前工程服务
server:
  # url路径前段
  context-path: /seller
  port: 8082
# 配置https加密
  ssl:
    enabled: true
    key-store: file:F:\javaPlugins\tomcat.keystore
    key-password: 941014

# 配置rpc服务器地址（名称自定义）**注意点，地址需要 / 结尾
rpc.manager.url: http://localhost:8081/manager/

# 指定spring开启的缓存类型
spring:
  cache:
    type: hazelcast
      #    暴露mq地址
  activemq:
    broker-url: tcp://localhost:61616
#    指定所有包都可以作为消息类型
    packages:
      trust-all: true
  datasource:
#    主库
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seller?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 1014
#   备份库
    backup:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seller-backup?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 1014
  jpa:
    show-sql: true
  swagger:
    title: 销售端API
    basePackage: com.ygq.finance.seller.controller
    description: 第三方销售机构相关的controller方法
